### ISSUE TITLE
config.cson entry wiped by package

### ISSUE THREAD

**Issue by lemongrassnginger** [dqsully/dqs-shell-commands#1]
Nice work on this! 

`.shell-commands` in each project is useful for project  but there are some commands I'd like to configure to run globally, ie in atom's config.cson. Still experiencing similar issues to atom-shell-commands with the config.cson entry being wiped when the package reads it. 

Love the use of finicky in the README :)

For reference, the issues in atom-shell-commands describing the similar problem:
 - [Instructions wrong?](https://github.com/skywind3000/atom-shell-commands/issues/10)
 - [config.cson](https://github.com/skywind3000/atom-shell-commands/issues/14)

**Comment by dqsully** [comment]
I'll try to add a global `.shell-commands.cson` file, probably stored under `~/.atom`, which has the exact same functionality.

**Comment by dqsully** [comment]
On that note, do you think it would be ok if I replaced the `config.cson` functionality entirely with that global file?

**Comment by dqsully** [comment]
I've gone ahead and done exactly that, also copying the user's preexisting config to the new file if it exists. Since there is no reason to using `config.cson` anymore, I am going to close this issue. However I wouldn't be surprised if I introduced another bug.

Thanks for the feedback 😄 !

**Comment by lemongrassnginger** [comment]
yep, new bug introduced :p  #4
