### ISSUE TITLE
disable autoclose on matches

### ISSUE THREAD

**Issue by jonatjano** [dqsully/dqs-shell-commands#10]
Hi,
I find the autoclose option so useful I'd like to use it anywere but I found one [one program (a linter)](https://github.com/FriendsOfPHP/PHP-CS-Fixer) where the exit code is 0 even when error are found. I have configured the matchs array but autoclose still close the console when a match is found.

so in short is there a way to prevent autoclose when a match is found without a care to return code ?

**Comment by dqsully** [comment]
Just pushed a new version with a new option: `options.keepOpenOnMatch`. If you enable this new option and `options.closeWhenFinished`, it should keep the console open when either the return code is non-zero or when something is matched by the `matchs` array.

**Comment by jonatjano** [comment]
Thank you ;)
