### ISSUE TITLE
unable to change project folders

### ISSUE THREAD

**Issue by lemongrassnginger** [dqsully/dqs-shell-commands#2]
I use [project-manager](https://atom.io/packages/project-manager) to switch between projects frequently. 

When dqs-shell-commands is enabled I can't use project-manger to switch projects (a restart of atom is required to switch). Disabling dqs-shell-commands restores the expected project-manager behaviour. Installing [atom-shell-commands](https://atom.io/packages/atom-shell-commands) instead doesn't cause an issue with project-manager, so I suspect it's something that's been introduced since the fork, maybe some way dqsshellcommands figures out which project it's in?

**Comment by lemongrassnginger** [comment]
Unable to add or remove project folders using [tree-view](https://atom.io/packages/tree-view) 
Linked to #3 ?

**Comment by dqsully** [comment]
It was a small typo, which is fixed now, but I just noticed another bug which needs to be squashed. Basically when you do change project folders now, it registers all of the keymaps and commands twice, running them twice with a single key press.

**Comment by dqsully** [comment]
Alright, new version is up, tell me if you have any problems.

Also, yes, atom-shell-commands did not have any integration with multiple projects, which is one of the first things I worked on. However I messed up a little bit with the project-based `.shell-commands.cson`.

**Comment by lemongrassnginger** [comment]
yep, seems fine now :)
